version: 2

defaults: &defaults
  docker:
    - image: node:latest
  working_directory: ~/repo

jobs:
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Run Unit Tests
          command: npm test
      - run:
          name: Build TypeScript
          command: npm run build
      - save_cache:
          paths:
            - dist/
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - persist_to_workspace:
          root: ~/repo
          paths: dist/
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm run do-publish
workflows:
  version: 2
  deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test