version: 2

defaults: &defaults
  docker:
    - image: node:latest
  working_directory: ~/repo

jobs:
  prepare:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - persist_to_workspace:
          root: ~/repo
          paths: .
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Build TypeScript
          command: npm run build
      - persist_to_workspace:
          root: ~/repo
          paths: dist/
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Run Unit Tests
          command: npm run test -- -R mocha-multi-reporters -O "configFile=mocha-config.json"
      - store_test_results:
          path: ~/repo/test-results.xml
      - store_artifacts:
          path: ~/repo/test-results.xml
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run: cp .npmrc dist/
      - run:
          name: Publish package
          command: npm run do-publish
workflows:
  version: 2
  deploy:
    jobs:
      - prepare
      - build:
          requires:
            - prepare
      - test:
          requires:
            - prepare
      - deploy:
          requires:
            - test
            - build
          filters:
            branches:
              only:
                - master
                - /release.*/
